[versions]
apv = "8.3.0"
ciceroneVersion = "7.1"
kotlin = "1.9.22"
library = "8.3.0"
androidx-junit = "1.1.5"
appcompat = "1.6.1"
constraintlayout = "2.1.4"
core-ktx = "1.10.1"
espresso-core = "3.5.1"
junit = "4.13.2"
material = "1.9.0"
bindingDelegateVersion = "1.5.9"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
cicerone = { module = "com.github.terrakok:cicerone", version.ref = "ciceroneVersion" }
junit = { module = "junit:junit", version.ref = "junit" }
material = { module = "com.google.android.material:material", version.ref = "material" }
viewBindingDelegate = { module = "com.github.kirich1409:viewbindingpropertydelegate-full", version.ref = "bindingDelegateVersion"}

[plugins]
androidApplication = { id = "com.android.application", version.ref = "apv"}
jetBrainsKotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin"}
library = { id = "com.android.library", version.ref = "library"}